### ISSUE TITLE
Compilation problems with switch-host-llvm (llvm 3.6)

### ISSUE THREAD

**Issue by caballa** [kdudka/predator#13]
Hi,
I'm trying to install Predator on a Mac.
The command I'm using is:

`./switch-host-llvm.sh <some_path_here>/share/llvm/cmake`

The version of LLVM is 3.6. 

While linking some library I get the error:

`ld: unknown option: --entry=plugin_init`

Do you have any intuition about what I missing?

I attach a log file.  

Thanks!
Jorge

[log.txt](https://github.com/kdudka/predator/files/737264/log.txt)

**Comment by kdudka** [comment]
Thank you for letting us know!  We do not test Predator on Mac ourselves, so we appreciate such feedback.

From the error message it looks like your linker does not support the ```--entry``` option.  I have pushed a workaround for the missing feature to an experimental branch -- could you please give it a try?
https://github.com/kdudka/predator/compare/mac

I have also rebased the ```darwin``` branch, which might also contain some useful quirks for your platform (sorry, I have no way to re-test myself whether it still does anything useful):
https://github.com/kdudka/predator/compare/darwin
