### ISSUE TITLE
Uninitialised or corrupted struct `cl_loc`

### ISSUE THREAD

**Issue by Toaster192** [kdudka/predator#99]
During my testing, I have encountered a bug that leads to the `.dot` output containing invalid UTF-8 characters (just some random memory dump).

This happens through this line https://github.com/kdudka/predator/blob/6654a89d7be4c1f7028b1c93bd2c5022caaa5736/sl/fixed_point_proxy.cc#L212 and I've only encountered this when having `/tests/gcc-adapter/C/26-Arrays-definitions.c` as the input.

Other information about my setup I manage to repeatedly reproduce this in:
Ubuntu 20.04, compiled for LLVM-10, `dump_fixed_point` enabled.

**Comment by kdudka** [comment]
This is most likely a problem with the `llvm` frontend.  Do you know which instruction triggers this problem?

I have quickly checked `cl/llvm/clplug.cc` for places where `cl->insn()` is called with a `cl_insn` struct that does not have the `loc` item initialized and spotted one place in `CLPass::handleAllocaInstruction()`.  Could you please try the following patch?
```diff
--- a/cl/llvm/clplug.cc
+++ b/cl/llvm/clplug.cc
@@ -1619,24 +1619,25 @@ void CLPass::handleAllocaInstruction(AllocaInst *I) {
     if (I->isArrayAllocation()) {
         handleOperand(I->getArraySize(), &arraySize);

         if (!isa<Constant>(I->getArraySize())) {
             getIntOperand(allocated->size, &typeSize);
             std::memset(&size, 0, sizeof(size));
             size.code = CL_OPERAND_VAR;
             size.scope = CL_SCOPE_FUNCTION;
             size.type = handleType(I->getArraySize()->getType());
             size.data.var = handleVariable(nullptr);

             mult.code = CL_INSN_BINOP;
+            mult.loc = cl_loc_known;
             mult.data.insn_binop.code = CL_BINOP_MULT;
             mult.data.insn_binop.src1 = &typeSize;
             mult.data.insn_binop.src2 = &arraySize;
             mult.data.insn_binop.dst = &size;
             cl->insn(cl, &mult);
         } else {
             handleOperand(I->getArraySize(), &size);
             // this is just an optimization
             size.data.cst.data.cst_int.value *= allocated->size;
         }
     } else {
         getIntOperand(allocated->size, &size);
```

**Comment by kdudka** [comment]
@Toaster192 Thank you for testing it!  I have submitted #100 to fix this.
